### ISSUE TITLE
Some files for this library?

### ISSUE THREAD

**Issue by dtboy1995** [hermesdj/mongoose-tx#1]
Is this library copy https://www.npmjs.com/package/mongoose-acid
copy is fine, but let me know it...
It's good that you copied the code and made it robust, but why even copy the readme.md and test cases and travis etc.?

**Comment by hermesdj** [comment]
Hey !

I took inspiration but wanted to add all the retry hooks advised by mongodb documentation. I will add a link in the README to your repository. I saw you were advancing a lot forward in the functionalities but I wanted only a basic version of transaction management ^^

I did not copy exactly the other files, I configured a travis for this project etc ;) (and I modified the test cases, they run with mocha and chai because I am more familiarised with it)

**Comment by dtboy1995** [comment]
you don't need to add my library to your readme, just let me know. The retry you added is also useful. It's all right. Have a good time

**Comment by dtboy1995** [comment]
You can remove the link about acid from your readme, because I think the retry added to your library will make the whole code more robust. I've written a little incomplete, and I hope the production environment will use your library.

**Comment by hermesdj** [comment]
It's fine, you deserve the credit ;)
